# FTPS Uploader 設定檔

# FTPS 伺服器設定
host=192.168.27.22
port=8421
user=MLS.OP200
pass=CMAKE#96

# 目錄設定
# 遠端上傳目錄 (選填)
remote_dir=\CSTP96.$DATA.SKDATA91
# 本地讀取目錄
local_dir=./uploads
# 日誌檔目錄
log_dir=./logs

# TLS 設定
use_implicit_tls=false
insecure_skip_verify=true

# 上傳時間限制 (選填)
# 格式: HH:mm-HH:mm
# 只有在指定時間範圍內且檔案存在時才會執行上傳
#allowed_time_range=00:00-23:59

# 要上傳的檔案清單
file_names.0.local_path=./uploads
file_names.0.files.0=test.txt:TEST
